### ISSUE TITLE
README guide cannot be followed fully without edits done 

### ISSUE THREAD

**Issue by vponoikoait** [nirmata/kyverno-notation-aws#130]
https://github.com/nirmata/kyverno-notation-aws/blob/main/README.md?plain=1#L37 ain't from public ECR registry 
[844333597536.dkr.ecr.us-west-2.amazonaws.com/kyverno-demo:v1](http://844333597536.dkr.ecr.us-west-2.amazonaws.com/kyverno-demo:v1) 
So any follow of README.md will result to errors related to auth

**Comment by vponoikoait** [comment]
I guess here preferable should be highlighted that you should build your own image for setup purposes, as it's not stated so, so that assumption is that image provided in documentation could be used for testing purposes - which wouldn't work as signer profile ain't available for everybody

**Comment by vishal-chdhry** [comment]
We expect users to create their own image for this and not follow this example, but I can understand how this can be assumed, I will update the readme to make this more clear
