### ISSUE TITLE
error: cannot unmarshal array into Go struct field RequestData.images of type types.ImageInfos

### ISSUE THREAD

**Issue by ajpaws** [nirmata/kyverno-notation-aws#37]
The latest version gives this error

2023-08-16T11:52:54.784Z        INFO    verifier/client.go:139  failed to decode {"images":["XXXXXXX.dkr.ecr.us-west-2.amazonaws.com/pause@sha256:33f19d2d8ba5fc17ac1099a840b0feac5f40bc6ac02d99891dbd13b0e204af4e"]}
: json: cannot unmarshal array into Go struct field RequestData.images of type types.ImageInfos

It used to work fine  earlier.  Also can we have a stable version release tags so we can pin to a specific version than latest?

**Comment by JimBugwadia** [comment]
@ajpaws - please check the sample policy in the latest version. The expected inputs have changed:

https://github.com/nirmata/kyverno-notation-aws/blob/main/configs/samples/kyverno-policy.yaml#L32C21-L32C27

**Comment by JimBugwadia** [comment]
@ajpaws - can you please verify the latest works for you?

**Comment by ajpaws** [comment]
@JimBugwadia thanks for the quick response. It works now.  Please note I created the workshop on the signer and using main branch https://catalog.workshops.aws/eks-security-immersionday/en-US/12-image-security/image-signing-with-aws-signer/3-signature-verification/2-verify-signature-with-kyverno-in-k8s. Please create a release / tag so we can pin to avoid any breaking in the workshop module

**Comment by vishal-chdhry** [comment]
@ajpaws We have a v1 beta1 tag available right now and we are working towards a v1 release which will be released soon. We will be releasing a v1 release candidate in a couple of days. It would be great if you test that out and add it to the workshop.

**Comment by JimBugwadia** [comment]
@ajpaws - thanks for sharing the workshop; this looks awesome!

**Comment by JimBugwadia** [comment]
Closing as this issue was resolved.
