### ISSUE TITLE
[Design] Improve contract design

### ISSUE THREAD

**Issue by eddycharly** [nirmata/kyverno-notation-aws#43]
The plugin should not be responsible of the path images belong to:
```json
{
  "verified": true,
  "message": "...",
  "results": [
    {
       "name": "container1",
       "path":  "/spec/containers/0",
       "image":  "ghcr.io/kyverno/test-verify-image@sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105"
    } 
  ]
}
```

And how can the plugin send a response where some image were successfully verified and others failed ?

**Comment by JimBugwadia** [comment]
Closing as I believe this is resolved. Please re-open and update if needed.
