### ISSUE TITLE
Im  getting "Error from server: admission webhook "mutate.kyverno.svc-fail" denied the request: mutation policy check-images error: failed to apply policy check-images rules [call-aws-signer-extension: failed to evaluate list response.results: failed to fetch data for APICall: HTTP 406 Not Acceptable: failed to verify container" when I try to run this on playground namespace on eks fargate. 

### ISSUE THREAD

**Issue by lahirushanaka** [nirmata/kyverno-notation-aws#48]
Im trying to implement this to our eks cluster which is run on fargate. Could you please help me to find the issue here ?
**Error:**
`kubectl -n playground run test --image=1234567899.dkr.ecr.ap-southeast-1.amazonaws.com/mailbox-processor:latest-dev
Error from server: admission webhook "mutate.kyverno.svc-fail" denied the request: mutation policy check-images error: failed to apply policy check-images rules [call-aws-signer-extension: failed to evaluate list response.results: failed to fetch data for APICall: HTTP 406 Not Acceptable: failed to verify container nphc-claimsflow-mailbox-processor: failed to verify image {{1234567899..dkr.ecr.ap-southeast-1.amazonaws.com mailbox-processor mailbox-processor latest-dev } /spec/containers/0/image}: signature verification failed
: failed to fetch data for APICall: HTTP 406 Not Acceptable: failed to verify container nphc-claimsflow-mailbox-processor: failed to verify image {{1234567899..dkr.ecr.ap-southeast-1.amazonaws.com/mailbox-processor latest-dev } /spec/containers/0/image}: signature verification failed`

**Trust Policy:**
`apiVersion: notation.nirmata.io/v1alpha1
kind: TrustPolicy
metadata:
  name: trustpolicy-sample
spec:
  version: '1.0'
  trustPolicyName: tp-playground
  trustPolicies:
  - name: aws-signer-tp
    registryScopes:
    - "*"
    signatureVerification:
      level: strict
      override: {}
    trustStores:
    - signingAuthority:aws-signer-ts
    trustedIdentities:
    - "arn:aws:signer:ap-southeast-1:1234567899:/signing-profiles/1234_signer"
---
apiVersion: notation.nirmata.io/v1alpha1
kind: TrustPolicy
metadata:
  name: trustpolicy-sample-fail
spec:
  version: '1.0'
  trustPolicyName: tp-playground-fail
  trustPolicies:
  - name: aws-signer-tp
    registryScopes:
    - "*"
    signatureVerification:
      level: strict
      override: {}
    trustStores:
    - signingAuthority:aws-signer-ts-fail
    trustedIdentities:
    - "arn:aws:signer:ap-southeast-1:1234567899:/signing-profiles/1234_signer"`

Kyverno-policy    
`apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-images     
spec:
  validationFailureAction: Enforce
  failurePolicy: Fail
  webhookTimeoutSeconds: 30
  schemaValidation: false
  rules:
  - name: call-aws-signer-extension
    match:
      any:
      - resources:
          namespaces:
          - playground
          kinds:
          - Pod
          operations:
            - CREATE
            - UPDATE
    context:
    - name: tlscerts
      apiCall:
        urlPath: "/api/v1/namespaces/kyverno-notation-aws/secrets/svc.kyverno-notation-aws.svc.tls-pair"
        jmesPath: "base64_decode( data.\"tls.crt\" )"
    - name: response
      apiCall:
        method: POST
        data:
        - key: images
          value: "{{images}}"
        - key: trustPolicy
          value: "tp-{{request.namespace}}"
        # - key: attestations
        #   value: 
        #   - imageReference: "*"
        #     type: 
        #     - name: sbom/example
        #       conditions:
        #         all:
        #         - key: \{{creationInfo.licenseListVersion}}
        #           operator: Equals
        #           value: "3.17"
        #           message: invalid license version
        service:
          url: https://svc.kyverno-notation-aws/checkimages
          caBundle: '{{ tlscerts }}'
    mutate:
      foreach:
      - list: "response.results"
        patchesJson6902: |-
            - path: {{ element.path }}
              op: replace
              value: {{ element.image }}`
    Service Account Permissions 
              
   `
   {
            "Action": [
                "ecr:UploadLayerPart",
                "ecr:PutImage",
                "ecr:InitiateLayerUpload",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetAuthorizationToken",
                "ecr:DescribeImages",
                "ecr:CompleteLayerUpload",
                "ecr:BatchGetImage",
                "ecr:BatchDeleteImage",
                "ecr:BatchCheckLayerAvailability"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "ECR"
        },
   {
            "Action": [
                "signer:SignPayload",
                "signer:ListTagsForResource",
                "signer:ListProfilePermissions",
                "signer:GetSigningProfile",
                "signer:GetRevocationStatus"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:signer:ap-southeast-1:1234567899:/signing-profiles/1234_signer",
                "*"
            ],
            "Sid": "signerpermission"
        }`

**Comment by vishal-chdhry** [comment]
Sorry for the late reply @lahirushanaka 

The error here seems to be that signature verification has failed
1. Is the image signed?
2. Are you using the right certificate 
3. Are the trust policies and trust store configured properly?

**Comment by JimBugwadia** [comment]
@lahirushanaka - any updates on this?

**Comment by lahirushanaka** [comment]
Hi @JimBugwadia and @vishal-chdhry , Sorry for the delay.
This can be ignore as we have discussed this with AWS support. as per them AWS signer is not supporting for the private clusters. which mean it need public access to verify the images.

**Comment by JimBugwadia** [comment]
@lahirushanaka - by "private clusters" do you mean your cluster has a private endpoint?

**Comment by JimBugwadia** [comment]
Confirmed that Signer currently does not currently support a VPC endpoint.

**Comment by lahirushanaka** [comment]
yeah, aws Signer dosen't have vpc end points. Since my cluster has been deployed on private subnet, nodes cannot connect to public singer endpoint.
