### ISSUE TITLE
[Bug] "Failed to initialize TUF client from  : updating local metadata and targets: error updating to TUF remote mirror

### ISSUE THREAD

**Issue by mihirgosai5** [nirmata/kyverno-notation-aws#52]
I am trying to deploy this service into an EKS cluster and running into a problem. The kyverno-admission-controller never completes deployment due to: 
`
I0920 11:13:33.446580       1 imageverifycache.go:12] setup/image-verify-cache "msg"="setup image verify cache..." "enabled"=true "maxsize"=1000 "ttl"=3600000000000
I0920 11:13:33.447245       1 tuf.go:14] setup/sigstore-tuf "msg"="setup tuf client for sigstore..." "tufmirror"="https://tuf-repo-cdn.sigstore.dev" "tufroot"=""
I0920 11:13:33.447269       1 tuf.go:23] setup/sigstore-tuf "msg"="Initializing TUF root" "tufmirror"="https://tuf-repo-cdn.sigstore.dev" "tufroot"=""
`
`
E0920 11:14:38.547749       1 error.go:19] setup/sigstore-tuf "msg"="Failed to initialize TUF client from  : updating local metadata and targets: error updating to TUF remote mirror: tuf: failed to download 8.root.json: Get \"https://tuf-repo-cdn.sigstore.dev/8.root.json\": dial tcp: lookup tuf-repo-cdn.sigstore.dev on 10.100.0.10:53: read udp 172.31.74.35:41468->10.100.0.10:53: read: connection refused\nremote status:{\n\t\"mirror\": \"https://tuf-repo-cdn.sigstore.dev\",\n\t\"metadata\": {}\n}" "error"="updating local metadata and targets: error updating to TUF remote mirror: tuf: failed to download 8.root.json: Get \"https://tuf-repo-cdn.sigstore.dev/8.root.json\": dial tcp: lookup tuf-repo-cdn.sigstore.dev on 10.100.0.10:53: read udp 172.31.74.35:41468->10.100.0.10:53: read: connection refused\nremote status:{\n\t\"mirror\": \"https://tuf-repo-cdn.sigstore.dev\",\n\t\"metadata\": {}\n}" "tufmirror"="https://tuf-repo-cdn.sigstore.dev" "tufroot"=""
`
Checking https://tuf-repo-cdn.sigstore.dev/8.root.json says the file doesn't exist so is there anything I can do to change the link it is trying to access?

**Comment by vishal-chdhry** [comment]
Thanks for reporting the issue @mihirgosai5, this bug is fixed in this PR: https://github.com/kyverno/kyverno/pull/8509

**Comment by mihirgosai5** [comment]
@vishal-chdhry Thank you!
